"""Generate `pages/scratchpads.toml` from sway's scratchpad-config.ini.

The same INI that drives sway's launch mode also drives this page, so a
single edit (in the INI) updates both.

INI sections become keys on a single deckctl page. Each section may declare:

  key=...           hotkey for sway launch mode (ignored here)
  label=...         display label (also used as a fallback icon name)
  command=...       used directly for `type=launch` entries
  type=launch       optional; marks an entry as a quicklaunch
  icon=...          optional; override the icon name

Scratchpad entries (no `type=launch`) execute
`~/.config/sway/bin/sway-scratchpad-launch.sh <section_name>`. Quicklaunch
entries run `command` verbatim.

Layout: back button at (0, 2). Remaining entries fill row-major, skipping
the back slot. Up to 14 entries fit; extras are skipped with a warning.

Usage:
    deckctl-gen-scratchpads                       # writes default location
    deckctl-gen-scratchpads --out -                # stdout
    deckctl-gen-scratchpads --in /alt/path.ini --out /alt/page.toml
"""

from __future__ import annotations

import argparse
import configparser
import os
import sys
from pathlib import Path

DEFAULT_ICONS: dict[str, str] = {
    "org.keepassxc.KeePassXC": "key",
    "org.telegram.desktop": "telegram",
    "vesktop": "discord",
    "signal": "signal",
    "feishin": "music",
    "org.speedcrunch.speedcrunch": "calculator",
    "_quicklaunch:vivaldi": "globe",
    "_quicklaunch:emoji": "face-smile-beam",
    "_quicklaunch:clipboard": "clipboard",
    "_quicklaunch:thunar": "folder",
    "_quicklaunch:commands": "terminal",
}

DEFAULT_INI = "~/.config/sway/scratchpad-config.ini"
DEFAULT_OUT = "~/.config/deckctl/pages/scratchpads.toml"
LAUNCH_HELPER = "~/.config/sway/bin/sway-scratchpad-launch.sh"

BACK_POS = (0, 2)
COLS, ROWS = 5, 3


def _grid_positions() -> list[tuple[int, int]]:
    """All (col, row) slots in row-major order, with the back slot reserved."""
    return [(c, r) for r in range(ROWS) for c in range(COLS) if (c, r) != BACK_POS]


def _toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _render(entries: list[tuple[tuple[int, int], str, str | None, str]]) -> str:
    """Render the TOML.

    entries: list of (pos, label, icon, on_press)
    """
    out = [
        "# GENERATED by deckctl-gen-scratchpads — do not edit by hand.",
        "# Source: ~/.config/sway/scratchpad-config.ini",
        "",
        "[page]",
        'name = "scratchpads"',
        'back = "main"',
        "",
        "[[keys]]",
        f"pos = [{BACK_POS[0]}, {BACK_POS[1]}]",
        'type = "command"',
        'icon = "go-previous"',
        'label = "Back"',
        'on_press = "back"',
    ]
    for pos, label, icon, on_press in entries:
        out.append("")
        out.append("[[keys]]")
        out.append(f"pos = [{pos[0]}, {pos[1]}]")
        out.append('type = "command"')
        if icon:
            out.append(f'icon = "{_toml_escape(icon)}"')
        out.append(f'label = "{_toml_escape(label)}"')
        out.append(f'on_press = "{_toml_escape(on_press)}"')
    out.append("")
    return "\n".join(out)


def _parse_ini(ini_path: Path) -> list[tuple[str, dict[str, str]]]:
    """Return [(section_name, settings_dict)] in INI declaration order."""
    cp = configparser.ConfigParser()
    cp.optionxform = str  # type: ignore[assignment]  # preserve case
    cp.read(ini_path)
    result: list[tuple[str, dict[str, str]]] = []
    for section in cp.sections():
        result.append((section, dict(cp.items(section))))
    return result


def build(ini_path: Path) -> str:
    sections = _parse_ini(ini_path)
    positions = iter(_grid_positions())

    entries: list[tuple[tuple[int, int], str, str | None, str]] = []
    skipped: list[str] = []

    for section, settings in sections:
        try:
            pos = next(positions)
        except StopIteration:
            skipped.append(section)
            continue

        label = settings.get("label", section)
        icon = settings.get("icon") or DEFAULT_ICONS.get(section)
        is_launch = settings.get("type") == "launch"

        if is_launch:
            cmd = settings.get("command")
            if not cmd:
                print(
                    f"warning: launch entry {section!r} has no command; skipping",
                    file=sys.stderr,
                )
                continue
            on_press = cmd
        else:
            on_press = f"{LAUNCH_HELPER} {section}"

        entries.append((pos, label, icon, on_press))

    if skipped:
        print(
            f"warning: {len(skipped)} entr{'y' if len(skipped) == 1 else 'ies'} "
            f"didn't fit on the deck and were skipped: {skipped}",
            file=sys.stderr,
        )

    return _render(entries)


def main() -> int:
    ap = argparse.ArgumentParser(prog="deckctl-gen-scratchpads")
    ap.add_argument(
        "--in", dest="ini", default=DEFAULT_INI,
        help=f"input INI path (default: {DEFAULT_INI})",
    )
    ap.add_argument(
        "--out", default=DEFAULT_OUT,
        help=f"output TOML path, or '-' for stdout (default: {DEFAULT_OUT})",
    )
    args = ap.parse_args()

    ini_path = Path(os.path.expanduser(args.ini))
    if not ini_path.exists():
        print(f"error: {ini_path} does not exist", file=sys.stderr)
        return 1

    rendered = build(ini_path)

    if args.out == "-":
        sys.stdout.write(rendered)
        return 0

    out_path = Path(os.path.expanduser(args.out))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered)
    print(f"wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
